### ISSUE TITLE
Adicionar links para torrents

### ISSUE THREAD

**Issue by rbrito** [camat-usp/Atividades-Online-Durante-a-Quarentena#34]
Olá...

Dada a natureza bastante volátil da genlib, uma técnica "anti censura" poderia, em parte, incentivar as pessoas a, também, (tentar) fazer download da versão em torrent, em vez de links diretos para os PDFs. Com isso, a disponibilidade pode aumentar e, com "alvos fragmentados", fazer "encerramento pode ficar difícil.

Ademais, "é justo" que quem faça download de um livro também ajude outros colegas com a distribuição dele, principalmente porque:

* há sites que oferecem os livros, mas são lentos (e.g., [Library Genesys 1][1], [Library Genesys 2][2])
* outros sites limitam os downloads a apenas 5 itens por dia (e.g., [Z-Library][3])

[1]: http://gen.lib.rus.ec/
[2]: https://libgen.lc/
[3]: https://b-ok.cc/

A criação de links para os torrents é relativamente simples/mecânica a partir dos links para os livros. Exemplos de links "diretos" e de seus correspondentes em torrents:

Direto: http://gen.lib.rus.ec/book/index.php?md5=61A6324B7F146E9B499C69C8A0D73F0E
Torrent: http://gen.lib.rus.ec/book/index.php?md5=61a6324b7f146e9b499c69c8a0d73f0e&oftorrent=

Direto: https://libgen.lc/ads.php?md5=61a6324b7f146e9b499c69c8a0d73f0e
Torrent: https://libgen.lc/book/index.php?md5=61a6324b7f146e9b499c69c8a0d73f0e&oftorrent=

Observações:

1. Parece que a essência é só "lascar `&oftorrent=`" ao final dos links para gerar o link para baixar os arquivos de torrent
2. Parece que os MD5 sums são case-insensitive

Bem, é isso.

Abraços,

Rogério.

**Comment by camat-usp** [comment]
Não pertence a este repositório. Vá para [github.com/camat-usp/Referencias-Bibliograficas](url).
